microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/idpaylolabpayment
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.rtd.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "512Mi"
      cpu: "50m"
    limits:
      memory: "768Mi"
      cpu: "100m"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url

  keyvault:
    name: "cstar-d-rtd-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"